### ISSUE TITLE
Why need to convert HEX to Binary

### ISSUE THREAD

**Issue by sinanopcommerce** [navtrack/navtrack#102]
![image](https://github.com/user-attachments/assets/f2498513-e631-438e-94a5-7bb311f55937)
 Why need to convert the HEX to Binary ?  Why not work directly with HEX

**Comment by andreisabau** [comment]
@sinanopcommerce MemoryStream / NetworkStream works with a byte array.

**Comment by sinanopcommerce** [comment]
Thank you @andreisabau, please close this issue.
