### ISSUE TITLE
Concox login not working

### ISSUE THREAD

**Issue by luizgustavogp** [navtrack/navtrack#23]
Hi, I´m testing a Concox device (crx3 mini) and I realize that login is not working. It looks like the return package is been calculated wrong because I compared it with [traccar](https://github.com/traccar/traccar). 
I tried to figure out what's going on and I´m suspecting CRC-ITU calculation.  
Do you need more information? 
Please, let me know if I can help you. Unfortunately, I couldn't find the problem yet.

If you want to test you can use [this](https://174.138.33.91/crx/web/ccx_eqp_lista.php?QDIAS=10)  to see all data, for example, login request and response, etc...

IP: 174.138.33.91 Port: 6969

**Comment by andreisabau** [comment]
Hi @luizgustavogp, I'm in the middle of releasing a complete new version of Navtrack, after I finish with the release I will take a look over your issue and fix it.

**Comment by luizgustavogp** [comment]
Hi @andreisabau . I see. So, yesterday a took a look at it and I realize that CRC-ITU calculation is correct, and the Login packet response match with the documentation, but for some reason, it does not work. Like I said when I compared it with traccar is different. The only part that is been different from taccar is the Information Serial Number. Navtrack set it with 00 05 and taccar set it with 00 01. I read the documentation again and I saw it:

> The serial number of the first GPRS data (including status packet
and data packet such as GPS, LBS) sent after booting is ‘1’, and
the serial number of data sent later at each time will be
automatically added ‘1’

When I force the **Information Serial Number**  has the 00 001 I have the same results of taccar, but it has not worked yet. I will investigate it more...

If you have same idea, please let me know.

**Comment by andreisabau** [comment]
@luizgustavogp I just pushed a fix for this: https://github.com/navtrack/navtrack/commit/41b231946ff19b9d11cff89a5c218f3026b32d3e
Indeed, the information serial number for the login packet is always 00 01. From my understanding for the following location packets the server should reply to the device with the same serial number.

**Comment by luizgustavogp** [comment]
Hey @andreisabau  I tried it a couple of days ago, but it didn't work yet. If you want to test it with my device, please let me know.

**Comment by andreisabau** [comment]
That would be nice, please join the Navtrack Discord server at https://discord.gg/N4ZxhB3y6h to set things up.

**Comment by andreisabau** [comment]
Closing this as it's been fixed in https://github.com/navtrack/navtrack/commit/a9b8482db689aee3265ac081081ed00935f3a983.
