### ISSUE TITLE
Support Teltonika FMB003

### ISSUE THREAD

**Issue by rslord8** [navtrack/navtrack#40]
Hi,
Can you support the Teltonika FMB003 tracker?

https://wiki.teltonika-gps.com/view/Codec#Codec_8_Extended

https://wiki.teltonika-gps.com/view/FMB003_Teltonika_Data_Sending_Parameters_ID

**Comment by andreisabau** [comment]
Hi @rslord8, this is not supported.

**Comment by nephthys** [comment]
Hi,
Are FMC003 and FMM003 (Teltonika) supported? If yes, can we retrieve and save on Navtrack the fuel consumption information  from OBD?
Thanks
