### ISSUE TITLE
docker compose missing environment varibles? 

### ISSUE THREAD

**Issue by DanielNagy** [navtrack/navtrack#41]
Hello,

I tried to deploy using the docker compose instructions as listed in the readme, however there was multiple issues. 
Firstly, Listener kept crashing (I resolved this by adding the mongo environment varibles to the listener service in the docker-compose file).
However, web service is still missing something. I am unable to register/login, as it tries to post to a  /undefined/ URI resulting in a 500 server error.
Is the docker-compose.yml file out of date? as referenced below?
`curl https://raw.githubusercontent.com/navtrack/navtrack/main/docker-compose.yml -o docker-compose.yml`

**Comment by andreisabau** [comment]
Hello @DanielNagy, running with Docker should be fixed now, let me know if you encounter any issues.
