### ISSUE TITLE
Galilosky Base block via iridium

### ISSUE THREAD

**Issue by djmomen** [navtrack/navtrack#42]
### Discussed in https://github.com/navtrack/navtrack/discussions/39

<div type='discussions-op-text'>

<sup>Originally posted by **djmomen** August 20, 2022</sup>
I hope you are fine.

I would like to know if Galilosky Base block via iridium works in your platform and the feature of receiving minimal data set is possible in your platform.
So does this sample

01003a01001c05fb1bad3330303233343036393930313031300000e4000062f7956803000b000f85402088970000000502000a55f74f8e522ef38b9400
Works in your platform

All the best</div>

**Comment by andreisabau** [comment]
Hello @djmomen, do you have a documentation for this protocol?
