### ISSUE TITLE
Error Invoking remote method

### ISSUE THREAD

**Issue by KARTHIKEYAN-KK** [navtrack/navtrack#46]
Hai I was trying to install Navtrack and install everything successfully but the listener container is not running and restarting continuously is there any solution to solve this I'm using a docker desktop for Windows.

![Screenshot_4](https://user-images.githubusercontent.com/99520670/194264319-a3bd9fb0-c5d5-4a32-b4b5-40ed2e6f79b2.jpg)
![Screenshot_6](https://user-images.githubusercontent.com/99520670/194264750-ee66afcf-236d-4b2a-beed-aca53715f424.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/99520670/194264622-32f9e19c-88bc-4415-9cb1-842fe5eaf313.jpg)

**Comment by andreisabau** [comment]
Hello @KARTHIKEYAN-KK, running Navtrack with docker should be fine now, let me know if you encounter any issues.
