### ISSUE TITLE
Axios Error

### ISSUE THREAD

**Issue by sinanopcommerce** [navtrack/navtrack#61]
ERROR in ../shared/src/api/authAxiosInstance.ts 9:33

Module parse failed: Unexpected token (9:33)
File was processed with these loaders:
 * ../node_modules/react-scripts/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ../node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| export const AUTH_AXIOS_INSTANCE = Axios.create();
| 
> export const authAxiosInstance = <T>(
|   config: AxiosRequestConfig
| ): Promise<T> => {

**Comment by andreisabau** [comment]
@sinanopcommerce this should be fixed now.
