### ISSUE TITLE
Is there any hope from this repo.

### ISSUE THREAD

**Issue by sinanopcommerce** [navtrack/navtrack#63]
Dear author, can you please help to run this repo on the windows server?

**Comment by andreisabau** [comment]
Running the application on Windows is currently a work in progress.

**Comment by sinanopcommerce** [comment]
> Running the application on Windows is currently a work in progress.

if you need a windows machine let me know. I can give you a VM at aws :).

**Comment by andreisabau** [comment]
@sinanopcommerce running the React app on Windows has been fixed.
