### ISSUE TITLE
 Error: MSB4020	The value "" of the "Project" attribute in element <Import> is invalid.	Navtrack.DataAccess.Services	

### ISSUE THREAD

**Issue by alishah151** [navtrack/navtrack#81]
Hi, I am trying to run this project on Windows and i keep getting this error when i run "dotnet build".
I have tried running "dotnet restore TheProject" But no success.

C:\Users\dev\Downloads\navtrack-main\navtrack-main\Directory.Build.props(8,5): error MSB4020: The value "" of the "Project" attribute in element <Import> is invalid. [C:\Users\dev\Downloads\navtrack-main\navtrack- 
main\backend\Navtrack.DataAccess\Navtrack.DataAccess.csproj]

i do not have much knowledge about .Net projects. I do not know what is wrong here.

I have .Net installed.
Docker installed.
I have windows 10.
I have used Visual Studio Community Edition 2022 and VS Code with Administer privileges too.

Any help would be appreciated. Thank you

**Comment by sinanopcommerce** [comment]
Most probably this man, does not use Visual Studio and windows. The error is simple, try to add the reference manually @

**Comment by sinanopcommerce** [comment]
Such a potential repo, but people get sucked whenever clone the repo.

**Comment by WaleedLab** [comment]
I have the same error.

**Comment by GeeSuth** [comment]
Hey @WaleedLab You can use my repo if Andrei does not accept my pull request. 
@andreisabau doing great job with this project.
![image](https://github.com/navtrack/navtrack/assets/10328974/757b1a3c-940c-49c3-b5cf-410a144ec7c5)

**Comment by andreisabau** [comment]
Thanks @GeeSuth for the contribution.

A fix is coming soon for this in [change-openapi-generator](https://github.com/navtrack/navtrack/tree/change-openapi-generator).

**Comment by andreisabau** [comment]
Hello everyone, this should now be fixed. Building and running in Windows should work fine now, let me know if you still encounter any issues.
