### ISSUE TITLE
Listener Error Teltonika

### ISSUE THREAD

**Issue by sinanopcommerce** [navtrack/navtrack#94]
"000000000000023D080A000000F9CEDA80B800D05D2FACFEB705A4000000C6090000000502EF00F00000011000001B74020B000000003566CEF40E000000003EA69BEF000000F9CEDA59A800D05D2FACFEB705A4000000C6090000000502EF00F00000011000001B74020B000000003566CEF40E000000003EA69BEF000000F9CEDA329800D05D2FACFEB705A4000000C6080000000502EF00F00000011000001B74020B000000003566CEF40E000000003EA69BEF000000F9CEDA07A000D05D2FACFEB705A4000000C6080000000502EF00F00000011000001B74020B000000003566CEF40E000000003EA69BEF000000F9CED9E09000D05D2FACFEB705A4000000C6070000000502EF00F00000011000001B74020B000000003566CEF40E000000003EA69BEF000000F9CED9B98000D05D2FACFEB705A4000000C6080000000502EF00F00000011000001B74020B000000003566CEF40E000000003EA69BEF000000F9CED9927000D05D2FACFEB705A4000000C6070000000502EF00F00000011000001B74020B000000003566CEF40E000000003EA69BEF000000F9CED96B6000D05D2FACFEB705A4000000C6070000000502EF00F00000011000001B74020B000000003566CEF40E000000003EA69BEF000000F9CED9445000D05D2FACFEB705A4000000C6080000000502EF00F00000011000001B74020B000000003566CEF40E000000003EA69BEF000000F9CED9212800D05D2FACFEB705A4000000C6090000F00502EF00F00000011000001B74020B000000003566CEF40E000000003EA69BEF0A00006A2F"

For this rawdata of teltonika FMB130 device listener cause error.

**Comment by andreisabau** [comment]
@sinanopcommerce this should be resolved in the latest version, let me know if it works.

**Comment by andreisabau** [comment]
@sinanopcommerce  this should be resolved in the latest version, please let me know if it works.

**Comment by sinanopcommerce** [comment]
ok I will take a new pull and let you know.
