### ISSUE TITLE
error during connect - docker

### ISSUE THREAD

**Issue by advtechsol** [navtrack/navtrack#98]
I'm probably doing something wrong or have missed a dependancy but on a fresh ubuntu install trying to use docker I get this error.

error during connect: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.43/containers/8e1eb3801893ae0a815a2015e7c3a48dbc8e2c2e016e8f67ddd94fd38357ffbf/start": EOF

**Comment by GeeSuth** [comment]
seems something related to your environment, trying to upgrade the docker version and also, maybe happen cause the network issues, 

and in some rare cause from docker server and you can check it from here: https://status.docker.com/

**Comment by advtechsol** [comment]
It was a fresh install of ubuntu 22.04 on a VPS and a fresh install of docker. 

I disabled ufw so I'm not sure...

**Comment by andreisabau** [comment]
@advtechsol I will test this in a similar environment and come back to you.

**Comment by advtechsol** [comment]
originally I installed docker by snap.

I just tried it again installing from source. 

I not longer get that error, but I cannot create an account I just have an endless spinning wheel on create account.

**Comment by GeeSuth** [comment]
> I not longer get that error, but I cannot create an account I just have an endless spinning wheel on create account.

can you check the console inside the browser and Network tab?

**Comment by advtechsol** [comment]
index-e5f09c97.js:94 
 POST http://localhost:3001/account net::ERR_CONNECTION_REFUSED

**Comment by GeeSuth** [comment]
> index-e5f09c97.js:94 POST http://localhost:3001/account net::ERR_CONNECTION_REFUSED

I cannot say the reason, if there a screenshot very well, but it's clear the backend app it's not started.

**Comment by advtechsol** [comment]
What do you want a screenshot of?

Am I missing a step?

1. install docker
2. download docker file
3. docker-compose up

**Comment by advtechsol** [comment]
<img width="1467" alt="Screenshot 2024-05-02 at 9 15 51 pm" src="https://github.com/navtrack/navtrack/assets/62219715/d6a22321-3f87-4079-8dd0-d848f6b212af">

**Comment by advtechsol** [comment]
<img width="1467" alt="Screenshot 2024-05-02 at 9 17 39 pm" src="https://github.com/navtrack/navtrack/assets/62219715/cf0ec560-22b3-4766-a20f-83cc35e3147f">

**Comment by GeeSuth** [comment]
> What do you want a screenshot of?
> 
> Am I missing a step?
> 
> 1. install docker
> 2. download docker file
> 3. docker-compose up

the front-end trying to connect to the back-end app using "http://localhost:3001/account" when the backend service running on the same domain of front-end, So, just change the URL,

**Comment by advtechsol** [comment]
I'm not sure what you mean

**Comment by advtechsol** [comment]
Are there any extra steps that are required if you are using a VPS?

**Comment by GeeSuth** [comment]
> Are there any extra steps that are required if you are using a VPS?

your system is working fine, I was able to create an account you can find it later in database, the domain is the problem only, 

![image](https://github.com/navtrack/navtrack/assets/10328974/930032f4-13b7-4953-a1c5-b86c32747a0d)

the frontend end app using the http://45.63.31.209:3000/ domain right? but the backend app using http://localhost:3001  
you need to change the http://localhost:3001 domain to http://45.63.31.209:3000 

and everything should work,

**Comment by GeeSuth** [comment]
![image](https://github.com/navtrack/navtrack/assets/10328974/388b45c5-644d-4bce-9aac-72f548cd5cb6)

**Comment by advtechsol** [comment]
@GeeSuth thats great.. 

how do I change the backend from localhost to my IP address?

**Comment by andreisabau** [comment]
@advtechsol By modifying the docker-compose.yml file line 10 you can change the backend URL on the frontend web app:

`- NAVTRACK_API_URL=http://localhost:3001`

**Comment by advtechsol** [comment]
ok I did that and got a bunch of new errors.

I need to run `docker compose up`

NOT `docker-compose up`

**Comment by GeeSuth** [comment]
@advtechsol  its working fine with you know? please close this issue!

**Comment by andreisabau** [comment]
@advtechsol what kind of errors are you still getting?

**Comment by GeeSuth** [comment]
> @advtechsol what kind of errors are you still getting?

from his [server](http://45.63.31.209:3000/), he able to resolve that problem, it's maybe related to update docker compose file,

**Comment by advtechsol** [comment]
sorry folks, ive been busy.

if you update your run guide from 

`docker-compose up`

TO

`docker compose up`

there are no errors
